*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /QAPS/V_CST_PRC.................................*
FORM GET_DATA_/QAPS/V_CST_PRC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /QAPS/CUSTO_PRC WHERE
(VIM_WHERETAB) .
    CLEAR /QAPS/V_CST_PRC .
/QAPS/V_CST_PRC-MANDT =
/QAPS/CUSTO_PRC-MANDT .
/QAPS/V_CST_PRC-ID_PROCESSO =
/QAPS/CUSTO_PRC-ID_PROCESSO .
/QAPS/V_CST_PRC-DESCRICAO =
/QAPS/CUSTO_PRC-DESCRICAO .
<VIM_TOTAL_STRUC> = /QAPS/V_CST_PRC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/QAPS/V_CST_PRC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /QAPS/V_CST_PRC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/QAPS/V_CST_PRC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /QAPS/CUSTO_PRC WHERE
  ID_PROCESSO = /QAPS/V_CST_PRC-ID_PROCESSO .
    IF SY-SUBRC = 0.
    DELETE /QAPS/CUSTO_PRC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /QAPS/CUSTO_PRC WHERE
  ID_PROCESSO = /QAPS/V_CST_PRC-ID_PROCESSO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /QAPS/CUSTO_PRC.
    ENDIF.
/QAPS/CUSTO_PRC-MANDT =
/QAPS/V_CST_PRC-MANDT .
/QAPS/CUSTO_PRC-ID_PROCESSO =
/QAPS/V_CST_PRC-ID_PROCESSO .
/QAPS/CUSTO_PRC-DESCRICAO =
/QAPS/V_CST_PRC-DESCRICAO .
    IF SY-SUBRC = 0.
    UPDATE /QAPS/CUSTO_PRC .
    ELSE.
    INSERT /QAPS/CUSTO_PRC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/QAPS/V_CST_PRC-UPD_FLAG,
STATUS_/QAPS/V_CST_PRC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/QAPS/V_CST_PRC.
  SELECT SINGLE * FROM /QAPS/CUSTO_PRC WHERE
ID_PROCESSO = /QAPS/V_CST_PRC-ID_PROCESSO .
/QAPS/V_CST_PRC-MANDT =
/QAPS/CUSTO_PRC-MANDT .
/QAPS/V_CST_PRC-ID_PROCESSO =
/QAPS/CUSTO_PRC-ID_PROCESSO .
/QAPS/V_CST_PRC-DESCRICAO =
/QAPS/CUSTO_PRC-DESCRICAO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/QAPS/V_CST_PRC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /QAPS/V_CST_PRC-ID_PROCESSO TO
/QAPS/CUSTO_PRC-ID_PROCESSO .
MOVE /QAPS/V_CST_PRC-MANDT TO
/QAPS/CUSTO_PRC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/QAPS/CUSTO_PRC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /QAPS/CUSTO_PRC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/QAPS/CUSTO_PRC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
