PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/QAPS/AREA CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /QAPS/AREA-ID_AREA .
    FIELD /QAPS/AREA-DESCRICAO .
    FIELD /QAPS/AREA-CREATED_BY .
    FIELD /QAPS/AREA-CREATED_IN .
    FIELD /QAPS/AREA-CREATED_ON .
    FIELD /QAPS/AREA-MODIFIED_BY .
    FIELD /QAPS/AREA-MODIFIED_IN .
    FIELD /QAPS/AREA-MODIFIED_ON .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /QAPS/AREA-ID_AREA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
